### ISSUE TITLE
Bugrock flag too much

### ISSUE THREAD

**Issue by RayanMamouni** [MILKv2/lightanticheat-config#1]
Bugrocks players flag really much >:(

**Comment by MILKv2** [comment]
which checks? can u list and provide a vid?

**Comment by RayanMamouni** [comment]
velocity A:
https://cdn.discordapp.com/attachments/1216476675395686412/1282007824733437992/Replay_2024-09-07_17-58-30_fein.mp4?ex=66de7313&is=66dd2193&hm=d0971c5961220b7d188f7fbf787d5ded0558d97cb97d8280130281521df3ccda&
